# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171102_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Align_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_wd', models.TextField()),
                ('ch_wd', models.TextField()),
                ('pos', models.TextField()),
                ('sense_id', models.IntegerField()),
                ('inv_index', models.TextField()),
                ('count', models.IntegerField()),
                ('similarity', models.TextField()),
            ],
        ),
    ]
