# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sense2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Align_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_wd', models.TextField()),
                ('ch_wd', models.TextField()),
                ('pos', models.TextField()),
                ('sense_id', models.IntegerField()),
                ('inv_index', models.TextField()),
                ('count', models.IntegerField()),
                ('similarity', models.FloatField()),
                ('en_prob', models.FloatField()),
                ('ch_prob', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Example_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.TextField()),
                ('eng_sent', models.TextField()),
                ('chi_sent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sense_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_wd', models.TextField()),
                ('ch_wd', models.TextField()),
                ('pos', models.TextField()),
                ('location', models.TextField()),
                ('number', models.TextField()),
                ('sense', models.TextField()),
            ],
        ),
    ]
