# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_align_wn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense_all2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_wd', models.TextField()),
                ('ch_wd', models.TextField()),
                ('pos', models.TextField()),
                ('location', models.TextField()),
                ('number', models.TextField()),
                ('sense', models.TextField()),
            ],
        ),
    ]
