# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_sense_all2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense_wn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('sense', models.TextField()),
            ],
        ),
    ]
