# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_sense_wn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_wd', models.TextField()),
                ('location', models.TextField()),
                ('ch_words', models.TextField()),
            ],
        ),
    ]
